<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Automaticky vygenerovaná migrace pro vytvoření tabulky messenger_messages.
 */
final class Version20251230131049 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Vytvoření tabulky pro ukládání zpráv v messengeru.';
    }

    public function up(Schema $schema): void
    {
        // Tato migrace vytvoří tabulku messenger_messages pro asynchronní zprávy
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        // Tato migrace odstraní tabulku messenger_messages
        $this->addSql('DROP TABLE messenger_messages');
    }
}
