<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migrace pro vytvoření tabulky globálního nastavení peněženky.
 * Tato tabulka uchovává preference uživatele, jako je hlavní měna a stav automatických aktualizací.
 */
final class Version20260104121838 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Vytvoření tabulky wallet_configuration pro globální nastavení modulu.';
    }

    /**
     * Provede změny v databázi (vytvoření tabulky).
     */
    public function up(Schema $schema): void
    {
        // Vytvoření tabulky pro konfiguraci s výchozími hodnotami pro auto-aktualizaci a hlavní měnu
        $this->addSql('CREATE TABLE wallet_configuration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, auto_update_enabled BOOLEAN DEFAULT true NOT NULL, main_currency VARCHAR(3) DEFAULT \'CZK\' NOT NULL, PRIMARY KEY (id))');
    }

    /**
     * Vrátí změny v databázi zpět (odstranění tabulky).
     */
    public function down(Schema $schema): void
    {
        // Odstranění tabulky konfigurace
        $this->addSql('DROP TABLE wallet_configuration');
    }
}
